### PR TITLE
Use GtkApplication and other new features

### PR DESCRIPTION
**Pull request by rluzynski**
Please review and accept.

### CODE REVIEW

**Comment by rluzynski** [comment]
There is something strange in this pull request, it seems to me that the commits have been reordered. However, in my repo https://github.com/rluzynski/bibledit-desktop/commits/gtk3 the order looks correct to me. Most of the time the order of commits does not matter but the commit ```Do not use and do not distribute the old icon``` mentions _the previous commit_ which should be ```New icons.``` If it is reordered then _the previous commit_ does not mean what I wanted to say.

**Comment by postiffm** [comment]
Here is what my current tree looks like---so you can see the order of commits, with the original gtk3 branch on the bottom (oldest on bottom, in other words).

3af5dc7 (HEAD -> rluzynski-gtkapplication4) Merge branch 'gtk3' of https://github.com/rluzynski/bibledit-desktop into rluzynski-gtkapplication4
7d718e6 [WIP] Application menu added
22920d7 [WIP] Port to GtkApplication framework
d6db43f [WIP] New icons
4818a80 (origin/gtk3, gtk3) Bump the required version of glib2.

**Comment by postiffm** [comment]
And now after I pulled the latest:

91fefcf (HEAD -> rluzynski-gtkapplication5) Merge rluzynski's 4 commits that implement GtkApplication.
a7118b2 Application menu added.
fcb2df4 Port to GtkApplication framework.
0360aeb Do not use and do not distribute the old icon.
b7f13bc New icons.
4818a80 (origin/gtk3, gtk3) Bump the required version of glib2.
463c9d4 CSS: Apply rounded top corners to the floating window

**Comment by postiffm** [comment]
This all is integrated into the gtk3 branch.

**Pull request merged**
