### PR TITLE
New po file

### PR DESCRIPTION
**Pull request by LAfricain**
New fr.po file to be merge, I hope this time the pull request will well be done ?? If not I can send the file manually.
I'm just surprised to see so much commits in the pull request...

### CODE REVIEW

**Comment by LAfricain** [comment]
Stylesheet.xml is now internationalized, please update the po.

**Comment by postiffm** [comment]
I think the extra commits happen in the pull request because you are not keeping up to date on my commits, or not rebasing. I'm not sure.

**Comment by postiffm** [comment]
I have cherry-picked d801b22, ee15ab3, and ef277c1. I think that is all I need to close this pull request. (I am not expert enough in git to figure out how to do this easily...I had to wade through commit conflicts between your pull request and my latest master.)

**Comment by postiffm** [comment]
Closed with commit 825f787..4f1fbad

**Comment by LAfricain** [comment]
> I think the extra commits happen in the pull request because you are not keeping up to date on my commits, or not rebasing. I'm not sure.

Yes I was surprised with all this extra commits! I don't know how to do to avoid this??

>I have cherry-picked d801b22, ee15ab3, and ef277c1.

Yes, this is OK!

**Pull request closed without merging**
