### PR TITLE
Clean up formatting with clang-format

### PR DESCRIPTION
**Pull request by PlasmaPower**
Don't view the diff in GitHub, view it locally. Once I get Travis setup, I'll integrate clang-format into that too.

Thoughts on the style guide?

### CODE REVIEW

**Comment by postiffm** [comment]
OK. Unfamiliar with clang-format. I'm not interested in having a
      bunch of whitespace changes in the code to have to wade through
      them while I'm looking for changes, if that is what it is doing.
      Also, I am unfamiliar with travis. Hope you can let me know before
      you commit our project to these things...
    
    
    On 7/19/2016 10:03 PM, Lee Bousfield
      wrote:
    
    
      Don't view the diff in GitHub, view it locally. Once I get
        Travis setup, I'll integrate clang-format into that too.
      Thoughts on the style guide?
      
      You can view, comment on, or merge this pull request online
        at:
        https://github.com/postiffm/bibledit-gtk/pull/4
      Commit Summary
      
        Clean up formatting with clang-format
      
      File Changes
      
         A .clang-format
          (88) 
         M src/assistantbackup.cpp
          (646) 
         M src/assistantbackup.h
          (57) 
         M src/assistantchanges.cpp
          (339) 
         M src/assistantchanges.h
          (47) 
         M src/assistantdeletekeyterms.cpp
          (169) 
         M src/assistantdeletekeyterms.h
          (32) 
         M src/assistantexport.cpp
          (1873) 
         M src/assistantexport.h
          (129) 
         M src/assistantimport.cpp
          (1013) 
         M src/assistantimport.h
          (98) 
         M src/assistantimportkeyterms.cpp
          (345) 
         M src/assistantimportkeyterms.h
          (46) 
         M src/assistantremoterepository.cpp
          (1102) 
         M src/assistantremoterepository.h
          (80) 
         M src/assistantresource.cpp
          (1152) 
         M src/assistantresource.h
          (110) 
         M src/assistantrestore.cpp
          (473) 
         M src/assistantrestore.h
          (52) 
         M src/assistants.cpp
          (172) 
         M src/assistants.h
          (44) 
         M src/backup.cpp
          (112) 
         M src/backup.h
          (23) 
         M src/bible.cpp
          (217) 
         M src/bible.h
          (53) 
         M src/bibledit-rdwrt.cpp
          (38) 
         M src/bibledit.cpp
          (172) 
         M src/biblenotes.cpp
          (78) 
         M src/biblenotes.h
          (34) 
         M src/bibletime.cpp
          (25) 
         M src/bibletime.h
          (15) 
         M src/bibleworks.cpp
          (597) 
         M src/bibleworks.h
          (41) 
         M src/bookdata.cpp
          (279) 
         M src/bookdata.h
          (46) 
         M src/books.cpp
          (316) 
         M src/books.h
          (61) 
         M src/categorize.cpp
          (154) 
         M src/categorize.h
          (44) 
         M src/chapterview.cpp
          (19) 
         M src/chapterview.h
          (35) 
         M src/check_capitalization.cpp
          (159) 
         M src/check_capitalization.h
          (60) 
         M src/check_chapters_verses.cpp
          (98) 
         M src/check_chapters_verses.h
          (42) 
         M src/check_compare_usfm.cpp
          (85) 
         M src/check_compare_usfm.h
          (43) 
         M src/check_count_characters.cpp
          (39) 
         M src/check_count_characters.h
          (27) 
         M src/check_count_usfms.cpp
          (25) 
         M src/check_count_usfms.h
          (26) 
         M src/check_count_words.cpp
          (34) 
         M src/check_count_words.h
          (36) 
         M src/check_markers_spacing.cpp
          (42) 
         M src/check_markers_spacing.h
          (29) 
         M src/check_matching_pairs.cpp
          (60) 
         M src/check_matching_pairs.h
          (46) 
         M src/check_parallel_passages.cpp
          (302) 
         M src/check_parallel_passages.h
          (63) 
         M src/check_ref_inventory.cpp
          (37) 
         M src/check_ref_inventory.h
          (31) 
         M src/check_repetition.cpp
          (47) 
         M src/check_repetition.h
          (29) 
         M src/check_sentence_structure.cpp
          (297) 
         M src/check_sentence_structure.h
          (50) 
         M src/check_unwanted_patterns.cpp
          (42) 
         M src/check_unwanted_patterns.h
          (27) 
         M src/check_unwanted_words.cpp
          (39) 
         M src/check_unwanted_words.h
          (26) 
         M src/check_validate_refs.cpp
          (63) 
         M src/check_validate_refs.h
          (27) 
         M src/check_validate_usfm.cpp
          (328) 
         M src/check_validate_usfm.h
          (36) 
         M src/checks.cpp
          (178) 
         M src/checks.h
          (93) 
         M src/clean.cpp
          (58) 
         M src/clean.h
          (20) 
         M src/color.cpp
          (33) 
         M src/color.h
          (26) 
         M src/combobox.cpp
          (41) 
         M src/combobox.h
          (33) 
         M src/compareutils.cpp
          (325) 
         M src/compareutils.h
          (29) 
         M src/completion.cpp
          (16) 
         M src/completion.h
          (18) 
         M src/compress.cpp
          (127) 
         M src/compress.h
          (20) 
         M src/concordance.cpp
          (502) 
         M src/config.xml.cpp
          (0) 
         I src/config.xml.h
          (0) 
         I src/constants.h
          (0) 
         I src/convert.cpp
          (0) 
         I src/convert.h
          (0) 
         I src/date_time_utils.cpp
          (0) 
         I src/date_time_utils.h
          (0) 
         I src/debug.h
          (0) 
         I src/dialogarea.cpp
          (0) 
         I src/dialogarea.h
          (0) 
         I src/dialogbook.cpp
          (0) 
         I src/dialogbook.h
          (0) 
         I src/dialogbooknames.cpp
          (0) 
         I src/dialogbooknames.h
          (0) 
         I src/dialogbulkspelling.cpp
          (0) 
         I src/dialogbulkspelling.h
          (0) 
         I src/dialogchapternumber.cpp
          (0) 
         I src/dialogchapternumber.h
          (0) 
         I src/dialogcheck.cpp
          (0) 
         I src/dialogcheck.h
          (0) 
         I src/dialogcheckbutton.cpp
          (0) 
         I src/dialogcheckbutton.h
          (0) 
         I src/dialogcompare.cpp
          (0) 
         I src/dialogcompare.h
          (0) 
         I src/dialogcompareprefs.cpp
          (0) 
         I src/dialogcompareprefs.h
          (0) 
         I src/dialogdate.cpp
          (0) 
         I src/dialogdate.h
          (0) 
         I src/dialogdictionary.cpp
          (0) 
         I src/dialogdictionary.h
          (0) 
         I src/dialogeditdictionary.cpp
          (0) 
         I src/dialogeditdictionary.h
          (0) 
         I src/dialogeditlist.cpp
          (0) 
         I src/dialogeditlist.h
          (0) 
         I src/dialogeditnote.cpp
          (0) 
         I src/dialogeditnote.h
          (0) 
         I src/dialogeditstatus.cpp
          (0) 
         I src/dialogeditstatus.h
          (0) 
         I src/dialogentry.cpp
          (0) 
         I src/dialogentry.h
          (0) 
         I src/dialogentry3.cpp
          (0) 
         I src/dialogentry3.h
          (0) 
         I src/dialogfilters.cpp
          (0) 
         I src/dialogfilters.h
          (0) 
         I src/dialogfindnote.cpp
          (0) 
         I src/dialogfindnote.h
          (0) 
         I src/dialogfixmarkers.cpp
          (0) 
         I src/dialogfixmarkers.h
          (0) 
         I src/dialogfontcolor.cpp
          (0) 
         I src/dialogfontcolor.h
          (0) 
         I src/dialoggotoreference.cpp
          (0) 
         I src/dialoggotoreference.h
          (0) 
         I src/dialoggui.cpp
          (0) 
         I src/dialoggui.h
          (0) 
         I src/dialogimportnotes.cpp
          (0) 
         I src/dialogimportnotes.h
          (0) 
         I src/dialoginsertnote.cpp
          (0) 
         I src/dialoginsertnote.h
          (0) 
         I src/dialoginserttable.cpp
          (0) 
         I src/dialoginserttable.h
          (0) 
         I src/dialoglistview.cpp
          (0) 
         I src/dialoglistview.h
          (0) 
         I src/dialoglistviewm.cpp
          (0) 
         I src/dialoglistviewm.h
          (0) 
         I src/dialogmaintenance.cpp
          (0) 
         I src/dialogmaintenance.h
          (0) 
         I src/dialogmerge.cpp
          (0) 
         I src/dialogmerge.h
          (0) 
         I src/dialogmychecks.cpp
          (0) 
         I src/dialogmychecks.h
          (0) 
         I src/dialognewstylesheet.cpp
          (0) 
         I src/dialognewstylesheet.h
          (0) 
         I src/dialognotes.cpp
          (0) 
         I src/dialognotes.h
          (0) 
         I src/dialognotestransfer.cpp
          (0) 
         I src/dialognotestransfer.h
          (0) 
         I src/dialognotesupdate.cpp
          (0) 
         I src/dialognotesupdate.h
          (0) 
         I src/dialogopenstylesheet.cpp
          (0) 
         I src/dialogopenstylesheet.h
          (0) 
         I src/dialogoriginreferences.cpp
          (0) 
         I src/dialogoriginreferences.h
          (0) 
         I src/dialogoutpost.cpp
          (0) 
         I src/dialogoutpost.h
          (0) 
         I src/dialogparallelbible.cpp
          (0) 
         I src/dialogparallelbible.h
          (0) 
         I src/dialogpdfviewer.cpp
          (0) 
         I src/dialogpdfviewer.h
          (0) 
         I src/dialogplanningedit.cpp
          (0) 
         I src/dialogplanningedit.h
          (0) 
         I src/dialogplanningsetup.cpp
          (0) 
         I src/dialogplanningsetup.h
          (0) 
         I src/dialogprintprefs.cpp
          (0) 
         I src/dialogprintprefs.h
          (0) 
         I src/dialogprintproject.cpp
          (0) 
         I src/dialogprintproject.h
          (0) 
         I src/dialogprintreferences.cpp
          (0) 
         I src/dialogprintreferences.h
          (0) 
         I src/dialogproject.cpp
          (0) 
         I src/dialogproject.h
          (0) 
         I src/dialogprojectnote.cpp
          (0) 
         I src/dialogprojectnote.h
          (0) 
         I src/dialogradiobutton.cpp
          (0) 
         I src/dialogradiobutton.h
          (0) 
         I src/dialogreferencesettings.cpp
          (0) 
         I src/dialogreferencesettings.h
          (0) 
         I src/dialogrefexchange.cpp
          (0) 
         I src/dialogrefexchange.h
          (0) 
         I src/dialogreplace.cpp
          (0) 
         I src/dialogreplace.h
          (0) 
         I src/dialogreplacing.cpp
          (0) 
         I src/dialogreplacing.h
          (0) 
         I src/dialogresourceconverter.cpp
          (0) 
         I src/dialogresourceconverter.h
          (0) 
         I src/dialogrevert.cpp
          (0) 
         I src/dialogrevert.h
          (0) 
         I src/dialogreviewanchors.cpp
          (0) 
         I src/dialogreviewanchors.h
          (0) 
         I src/dialogsearchspecial.cpp
          (0) 
         I src/dialogsearchspecial.h
          (0) 
         I src/dialogselectbooks.cpp
          (0) 
         I src/dialogselectbooks.h
          (0) 
         I src/dialogselectchapters.cpp
          (0) 
         I src/dialogselectchapters.h
          (0) 
         I src/dialogshownotes.cpp
          (0) 
         I src/dialogshownotes.h
          (0) 
         I src/dialogstylesheet.cpp
          (0) 
         I src/dialogstylesheet.h
          (0) 
         I src/dialogsystemlog.cpp
          (0) 
         I src/dialogsystemlog.h
          (0) 
         I src/dialogtaskduration.cpp
          (0) 
         I src/dialogtaskduration.h
          (0) 
         I src/dialogtext2pdf.cpp
          (0) 
         I src/dialogtext2pdf.h
          (0) 
         I src/dialogtextreplacement.cpp
          (0) 
         I src/dialogtextreplacement.h
          (0) 
         I src/dialogtidy.cpp
          (0) 
         I src/dialogtidy.h
          (0) 
         I src/dialogviewplanning.cpp
          (0) 
         I src/dialogviewplanning.h
          (0) 
         I src/dialogwait.cpp
          (0) 
         I src/dialogwait.h
          (0) 
         I src/dialogwordlist.cpp
          (0) 
         I src/dialogwordlist.h
          (0) 
         I src/dialogxetex.cpp
          (0) 
         I src/dialogxetex.h
          (0) 
         I src/dialogxfernotes2text.cpp
          (0) 
         I src/dialogxfernotes2text.h
          (0) 
         I src/dialogyesnoalways.cpp
          (0) 
         I src/dialogyesnoalways.h
          (0) 
         I src/directories.cpp
          (0) 
         I src/directories.h
          (0) 
         I src/displayprojectnotes.cpp
          (0) 
         I src/displayprojectnotes.h
          (0) 
         I src/editor.cpp
          (0) 
         I src/editor.h
          (0) 
         I src/editor_aids.cpp
          (0) 
         I src/editor_aids.h
          (0) 
         I src/editoractions.cpp
          (0) 
         I src/editoractions.h
          (0) 
         I src/export_translation_notes.cpp
          (0) 
         I src/export_translation_notes.h
          (0) 
         I src/export_utils.cpp
          (0) 
         I src/export_utils.h
          (0) 
         I src/fixmarkers.cpp
          (0) 
         I src/fixmarkers.h
          (0) 
         I src/floatingwindow.cpp
          (0) 
         I src/floatingwindow.h
          (0) 
         I src/generalconfig.cpp
          (0) 
         I src/generalconfig.h
          (0) 
         I src/git-exec.cpp
          (0) 
         I src/git-exec.h
          (0) 
         I src/git.cpp
          (0) 
         I src/git.h
          (0) 
         I src/greek.cpp
          (0) 
         I src/greek.h
          (0) 
         I src/gtkwrappers.cpp
          (0) 
         I src/gtkwrappers.h
          (0) 
         I src/gui.cpp
          (0) 
         I src/gui.h
          (0) 
         I src/gui_display_changes.cpp
          (0) 
         I src/gui_display_changes.h
          (0) 
         I src/gui_features.cpp
          (0) 
         I src/gui_features.h
          (0) 
         I src/gui_navigation.cpp
          (0) 
         I src/gui_navigation.h
          (0) 
         I src/guiselectbibles.cpp
          (0) 
         I src/guiselectbibles.h
          (0) 
         I src/guiselectproject.cpp
          (0) 
         I src/guiselectproject.h
          (0) 
         I src/gwrappers.cpp
          (0) 
         I src/gwrappers.h
          (0) 
         I src/help.cpp
          (0) 
         I src/help.h
          (0) 
         I src/highlight.cpp
          (0) 
         I src/highlight.h
          (0) 
         I src/html.cpp
          (0) 
         I src/html.h
          (0) 
         I src/htmlbrowser.cpp
          (0) 
         I src/htmlbrowser.h
          (0) 
         I src/htmlwriter.cpp
          (0) 
         I src/htmlwriter.h
          (0) 
         I src/htmlwriter2.cpp
          (0) 
         I src/htmlwriter2.h
          (0) 
         I src/httpd.cpp
          (0) 
         I src/httpd.h
          (0) 
         I src/hyphenate.cpp
          (0) 
         I src/hyphenate.h
          (0) 
         I src/import.cpp
          (0) 
         I src/import.h
          (0) 
         I src/java.cpp
          (0) 
         I src/java.h
          (0) 
         I src/keyboard.cpp
          (0) 
      
      Patch Links:
      
        https://github.com/postiffm/bibledit-gtk/pull/4.patch
        https://github.com/postiffm/bibledit-gtk/pull/4.diff
      
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it
          on GitHub, or mute
          the thread.

**Comment by PlasmaPower** [comment]
> Also, I am unfamiliar with travis. Hope you can let me know before you commit our project to these things...

Everything I've done for master recently has been through pull requests, these aren't on master yet but they will be if we merge these. I'm planning to continue in this manner.

**Comment by PlasmaPower** [comment]
> I'm not interested in having bunch of whitespace changes in the code to have to wade through them while I'm looking for changes, if that is what it is doing.

I fully agree there. I'm not expecting this PR to be merged, it's just a starting point.

I think I might have a solution to this, rewrite all commits to agree to the formatting guidelines. I've pushed the rewritten commits to the branch `commit-reformat`. Pushing them to master would require a force push (can't be done through a pull request) so I'd like you're approval before I do that (and remember to pull after I do that so we don't have issues there).

Also, do you agree with the current formatting guidelines that I've implemented? Try checking out `commit-reformat` and looking through some code there. I can change the guidelines of course. One thing I'm not sure about is the column limit of 80, that's standard but we might want to increase that or shorten variable names in the future.

**Comment by PlasmaPower** [comment]
Could you avoid responding to GitHub issues in your email client and instead use the GitHub webpage? GitHub doesn't seem to like your email client's response quoting, so the original text shows up as part of your response which clogs up the comment. I've edited out the quoted response from your most recent comment as it was especially long, but [here's what it was before that](https://gist.github.com/PlasmaPower/fe9663770e2f9940d26c1c75fe705572).

**Comment by postiffm** [comment]
OK, I can try to use the github webpage. I'm not interested in automatically rewriting commits to change the formatting I've put on the code. I want the code I write in the repository "as is." I admit to having a problem with Emacs versus Notepad++ (my currently preferred Windows text editor) not agreeing on tab stops and other spacing issues, but I've been doing OK so far with it. Also, there are many lines way longer than 80 characters in the codebase, and I don't care to work on changing them at the moment. My screen is plenty wide enough to view everything.

**Comment by postiffm** [comment]
I've got to quit for the night. I don't know how to view the style guide in a quick way.

**Comment by PlasmaPower** [comment]
Future commits will be "as is", this is about past commits, as we have various indentation, trailing lines, and bracket styles. It'd be nice to standardize. I'll remove the line length limit. I'm not currently working on enforcing a style (we might do that after Travis though, IDK).

The style guide is in `.clang-format`, but you might try just viewing some cpp files and seeing how they look.

**Pull request closed without merging**
