### PR TITLE
Localization and new po file

### PR DESCRIPTION
**Pull request by LAfricain**
I localized some files and create a new fr.po and en.pot

### CODE REVIEW

**Comment by postiffm** [comment]
Is this pull request still relevant?

**Comment by LAfricain** [comment]
No. I'll work on github.

Le 16/02/2018 à 14:27, Matt Postiff a écrit :

**Comment by postiffm** [comment]
@LAfricain can you comment on whether this pull request is still relevant?

**Comment by LAfricain** [comment]
No, it's not relevant!

**Pull request closed without merging**
